# Generated by Django 3.0.5 on 2020-04-23 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compras_envios',
            name='costo_total',
        ),
    ]
