# Generated by Django 3.0.5 on 2020-04-23 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_productos_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compras_envios',
            name='num_referencia',
            field=models.IntegerField(max_length=12, null=True),
        ),
    ]
